// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var mixin;
    return mixin = function(Class, Mixin) {
      var construct, f, name, prop, proto, _ref;
      f = function() {};
      f.prototype = Class.prototype;
      proto = new f();
      _ref = Mixin.prototype;
      for (name in _ref) {
        prop = _ref[name];
        if (Mixin.prototype.hasOwnProperty(name)) {
          proto[name] = prop;
        }
      }
      construct = function() {
        Class.apply(this, arguments);
        Mixin.apply(this, arguments);
        return this;
      };
      construct.prototype = proto;
      return constrcut;
    };
  });

}).call(this);
