// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var mixin, _getNewProto;
    _getNewProto = function(Class, mixinProto) {
      var f, name, prop, proto;
      f = function() {};
      f.prototype = Class.prototype;
      proto = new f();
      for (name in mixinProto) {
        prop = mixinProto[name];
        if (mixinProto.hasOwnProperty(name)) {
          proto[name] = prop;
        }
      }
      return proto;
    };
    return mixin = function(Class, Mixin, beforeConstruct) {
      var construct, haveConstructor, mixinProto, proto;
      if (beforeConstruct == null) {
        beforeConstruct = false;
      }
      haveConstructor = typeof Mixin === "function";
      mixinProto = haveConstructor ? Mixin.prototype : Mixin;
      proto = _getNewProto(Class, mixinProto);
      if (haveConstructor) {
        if (beforeConstruct) {
          construct = function() {
            Mixin.apply(this, arguments);
            Class.apply(this, arguments);
            return this;
          };
        } else {
          construct = function() {
            Class.apply(this, arguments);
            Mixin.apply(this, arguments);
            return this;
          };
        }
      } else {
        construct = function() {
          Class.apply(this, arguments);
          return this;
        };
      }
      construct.prototype = proto;
      proto.constructor = construct;
      return construct;
    };
  });

}).call(this);
