// Generated by CoffeeScript 1.6.2
/*
Class may be used as mixin or base class for classes that should support events

@author Vitalii [Nayjest] Stepanenko <gmail@vitaliy.in>
*/


(function() {
  define(['components/jquery/jquery'], function() {
    var EventsMixin;

    return EventsMixin = (function() {
      function EventsMixin() {
        var _ref;

        if ((_ref = this.eventHandlers) == null) {
          this.eventHandlers = {};
        }
      }

      EventsMixin.prototype.on = function(eventName, handler) {
        var callbacks;

        callbacks = this.eventHandlers[eventName];
        if (!callbacks) {
          this.eventHandlers[eventName] = callbacks = $.Callbacks();
        }
        return callbacks.add(handler);
      };

      EventsMixin.prototype.fireEvent = function(eventName, options) {
        var callbacks;

        callbacks = this.eventHandlers[eventName];
        if ($callbacks) {
          return $callbacks.fireWith(this, options);
        }
      };

      return EventsMixin;

    })();
  });

}).call(this);
