// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/jquery/jquery'], function() {
    var EventsMixin;
    return EventsMixin = (function() {

      function EventsMixin() {
        var _ref;
        if ((_ref = this.eventHandlers) == null) {
          this.eventHandlers = {};
        }
      }

      EventsMixin.prototype.on = function(eventName, handler) {
        var callbacks;
        callbacks = this.eventHandlers[eventName];
        if (!callbacks) {
          this.eventHandlers[eventName] = callbacks = $.Callbacks();
        }
        return callbacks.add(handler);
      };

      EventsMixin.prototype.fireEvent = function(eventName, options) {
        var callbacks;
        callbacks = this.eventHandlers[eventName];
        if ($callbacks) {
          return $callbacks.fireWith(this, options);
        }
      };

      return EventsMixin;

    })();
  });

}).call(this);
